//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fidelitas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        public int iID { get; set; }
        public string vNombre { get; set; }
        public int iEstilo { get; set; }
        public Nullable<int> iCilindraje { get; set; }
        public int iCosto { get; set; }
        public string vTransmision { get; set; }
        public int iCantidadPuertas { get; set; }
        public int iAno { get; set; }
        public string vNombreMarca { get; set; }
    }
}
